name: Build
on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  build_for_linux:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y --no-install-recommends \
            build-essential
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.version=v0.1.0 -X main.revision=HEAD" -o git-cm .
  build_for_macos:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - name: Install build dependencies
        run: brew install coreutils
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.version=v0.0.0 -X main.revision=HEAD" -o git-cm .
  build_for_windows:
    if: github.event.pull_request.draft == false
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.version=v0.0.0 -X main.revision=HEAD" -o git-cm.exe .
